version: '3.8'
services:
  postgresdb:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
  python:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgresdb
    command:
      tail -f /dev/null
volumes:
  db:
    driver: local